export const COLS = 10;
export const DEFAULT_ROWS = 20;
export const MAX_ROUND = 20;
export const GAME_TIMING = {
  LOCK_DELAY_START: 520,
  LOCK_DELAY_STEP: 55,
  LOCK_DELAY_MIN: 120,
  PLAYER_FALL_INTERVAL: 760,
  PLAYER_SLOW_FACTOR: 0.55,
  ENEMY_SLOW_FACTOR: 2.8,
  GARBAGE_ARM_DELAY: 3000,
  GARBAGE_DELAY_ON_CLEAR: 1000,
  GARBAGE_MIN_ARM: 600,
  COOLANT_SLOW: 500,
  AUTO_SAVE_INTERVAL: 5000,
  ENEMY_ABILITY_INTERVAL: 6500,
  BATTLE_WIN_DELAY: 1400,
  BATTLE_LOSS_DELAY: 1200,
  BOMB_FX_FLASH: 520,
  EXPLOSION_DROP_DELAY: 150,
  CLEAR_FEEDBACK_FLASH: 1100,
  COMBO_BREAK_FLASH: 900,
  TOUCH_FIRST_DELAY: 240,
  TOUCH_SOFT_FIRST_DELAY: 120,
  TOUCH_REPEAT_DELAY: 110,
  TOUCH_SOFT_REPEAT_DELAY: 70,
  KEY_REPEAT_FIRST_DELAY: 180,
  KEY_REPEAT_DELAY: 90,
  KEY_REPEAT_FAST_DELAY: 45
};

export const TYPES = {
  EMPTY: 'empty',
  GARBAGE: 'garbage',
  I: 'I',
  J: 'J',
  L: 'L',
  O: 'O',
  S: 'S',
  T: 'T',
  Z: 'Z',
  POWER_I: 'POWER_I',
  POWER_T: 'POWER_T',
  POWER_S: 'POWER_S',
  CROSS: 'CROSS',
  BOMB: 'BOMB',
  BOMB_I: 'BOMB_I',
  MANA_T: 'MANA_T',
  MANA_L: 'MANA_L',
  PURGE_O: 'PURGE_O',
  CLEANSE_J: 'CLEANSE_J',
  HEAVY_JUNK: 'HEAVY_JUNK',
  POWER_CROSS: 'POWER_CROSS',
  WIDE_JUNK: 'WIDE_JUNK',
  INSTANT_STRIKE: 'INSTANT_STRIKE',
  INSTANT_GUARD: 'INSTANT_GUARD',
  INSTANT_MANA: 'INSTANT_MANA',
  INSTANT_PURGE: 'INSTANT_PURGE',
  POWER_Z: 'POWER_Z',
  MANA_Z: 'MANA_Z',
  BOMB_Z: 'BOMB_Z',
  CLEANSE_Z: 'CLEANSE_Z',
  POWER_L: 'POWER_L',
  MANA_I: 'MANA_I',
  BOMB_T: 'BOMB_T',
  CLEANSE_S: 'CLEANSE_S',
  COOLANT_J: 'COOLANT_J',
  BOUNTY_O: 'BOUNTY_O',
  WARD_Z: 'WARD_Z',
  WARD_I: 'WARD_I',
  BOMB_J: 'BOMB_J',
  BOMB_L: 'BOMB_L',
  MANA_O: 'MANA_O',
  BOUNTY_S: 'BOUNTY_S',
  COOLANT_T: 'COOLANT_T',
  COOLANT_Z: 'COOLANT_Z',
  POWER_PENTA: 'POWER_PENTA',
  COOLANT: 'COOLANT',
  COMBO_CHARGE: 'COMBO_CHARGE',
  BOUNTY: 'BOUNTY',
  UNSTABLE: 'UNSTABLE',
  LEAD: 'LEAD',
  WARD_T: 'WARD_T',
  GLASS: 'GLASS',
  TIMEBOMB: 'TIMEBOMB',
  OVERDRIVE_PENTA: 'OVERDRIVE_PENTA',
  MEGA_CLEANSE: 'MEGA_CLEANSE',
  PANIC_WALL: 'PANIC_WALL',
  FLASH_I: 'FLASH_I',
  AID_O: 'AID_O',
  POWER_J: 'POWER_J',
  POWER_O: 'POWER_O',
  BOMB_S: 'BOMB_S',
  MANA_J: 'MANA_J',
  MANA_S: 'MANA_S',
  CLEANSE_I: 'CLEANSE_I',
  CLEANSE_L: 'CLEANSE_L',
  CLEANSE_T: 'CLEANSE_T',
  COOLANT_O: 'COOLANT_O',
  COOLANT_L: 'COOLANT_L',
  COOLANT_S: 'COOLANT_S',
  BOUNTY_I: 'BOUNTY_I',
  BOUNTY_J: 'BOUNTY_J',
  BOUNTY_T: 'BOUNTY_T',
  BOUNTY_Z: 'BOUNTY_Z',
  WARD_J: 'WARD_J',
  WARD_L: 'WARD_L',
  WARD_O: 'WARD_O',
  WARD_S: 'WARD_S',
  COMBO_I: 'COMBO_I',
  COMBO_J: 'COMBO_J',
  COMBO_L: 'COMBO_L',
  COMBO_O: 'COMBO_O',
  COMBO_S: 'COMBO_S',
  COMBO_Z: 'COMBO_Z',
  CRUSHER: 'CRUSHER',
  DISPEL_T: 'DISPEL_T',
  DISPEL_O: 'DISPEL_O',
  DISPEL_I: 'DISPEL_I'
};

export const BASE_TYPES = [TYPES.I, TYPES.J, TYPES.L, TYPES.O, TYPES.S, TYPES.T, TYPES.Z];
export const TIERS = {
  BRONZE: 'bronze',
  SILVER: 'silver',
  GOLD: 'gold'
};
export const TIER_ORDER = [TIERS.BRONZE, TIERS.SILVER, TIERS.GOLD];
export const TIER_LABELS = {
  [TIERS.BRONZE]: 'BRONZE',
  [TIERS.SILVER]: 'SILVER',
  [TIERS.GOLD]: 'GOLD'
};

export const COLORS = {
  [TYPES.I]: '#00d9e8',
  [TYPES.J]: '#3767ff',
  [TYPES.L]: '#f0a12a',
  [TYPES.O]: '#e8d93a',
  [TYPES.S]: '#23d15f',
  [TYPES.T]: '#9c54ff',
  [TYPES.Z]: '#f24b52',
  [TYPES.POWER_I]: '#ff3b8d',
  [TYPES.POWER_T]: '#d85cff',
  [TYPES.POWER_S]: '#31ff87',
  [TYPES.CROSS]: '#d8f7ff',
  [TYPES.BOMB]: '#ff6a22',
  [TYPES.BOMB_I]: '#ff8b2f',
  [TYPES.MANA_T]: '#45f0bd',
  [TYPES.MANA_L]: '#56ffd1',
  [TYPES.PURGE_O]: '#f5f2ff',
  [TYPES.CLEANSE_J]: '#c6d8ff',
  [TYPES.HEAVY_JUNK]: '#6d5f73',
  [TYPES.POWER_CROSS]: '#ffb0d0',
  [TYPES.WIDE_JUNK]: '#58515f',
  [TYPES.INSTANT_STRIKE]: '#ffcc66',
  [TYPES.INSTANT_GUARD]: '#80a8ff',
  [TYPES.INSTANT_MANA]: '#63ffdd',
  [TYPES.INSTANT_PURGE]: '#f4f7ff',
  [TYPES.POWER_Z]: '#ff5a6f',
  [TYPES.MANA_Z]: '#4ad0a8',
  [TYPES.BOMB_Z]: '#ff7a3a',
  [TYPES.CLEANSE_Z]: '#d8e4ff',
  [TYPES.POWER_L]: '#ff9b4a',
  [TYPES.MANA_I]: '#72ffe1',
  [TYPES.BOMB_T]: '#ff7042',
  [TYPES.CLEANSE_S]: '#d9f0ff',
  [TYPES.COOLANT_J]: '#88dcff',
  [TYPES.BOUNTY_O]: '#ffd052',
  [TYPES.WARD_Z]: '#8fb7ff',
  [TYPES.WARD_I]: '#9cc2ff',
  [TYPES.BOMB_J]: '#ff7d35',
  [TYPES.BOMB_L]: '#ff8a42',
  [TYPES.MANA_O]: '#68f2cf',
  [TYPES.BOUNTY_S]: '#f1c94a',
  [TYPES.COOLANT_T]: '#91e4ff',
  [TYPES.COOLANT_Z]: '#87d6ff',
  [TYPES.POWER_PENTA]: '#ff79c0',
  [TYPES.COOLANT]: '#9fe8ff',
  [TYPES.COMBO_CHARGE]: '#ffd84a',
  [TYPES.BOUNTY]: '#f4c025',
  [TYPES.UNSTABLE]: '#d23bff',
  [TYPES.LEAD]: '#8a8f9c',
  [TYPES.WARD_T]: '#a7c8ff',
  [TYPES.GLASS]: '#bfefff',
  [TYPES.TIMEBOMB]: '#ff4d4d',
  [TYPES.OVERDRIVE_PENTA]: '#ff2d6f',
  [TYPES.MEGA_CLEANSE]: '#eafcff',
  [TYPES.PANIC_WALL]: '#7fb6ff',
  [TYPES.FLASH_I]: '#ffe66b',
  [TYPES.AID_O]: '#b9ffe0',
  [TYPES.POWER_J]: '#ff6f9c',
  [TYPES.POWER_O]: '#ff5c8a',
  [TYPES.BOMB_S]: '#ff7a3a',
  [TYPES.MANA_J]: '#4ad6c0',
  [TYPES.MANA_S]: '#52e8c4',
  [TYPES.CLEANSE_I]: '#cfe2ff',
  [TYPES.CLEANSE_L]: '#cdd9ff',
  [TYPES.CLEANSE_T]: '#d6e0ff',
  [TYPES.COOLANT_O]: '#9be4ff',
  [TYPES.COOLANT_L]: '#90dcff',
  [TYPES.COOLANT_S]: '#8ad6ff',
  [TYPES.BOUNTY_I]: '#f4c63a',
  [TYPES.BOUNTY_J]: '#f1c230',
  [TYPES.BOUNTY_T]: '#f6cf45',
  [TYPES.BOUNTY_Z]: '#efc52a',
  [TYPES.WARD_J]: '#86adff',
  [TYPES.WARD_L]: '#93b9ff',
  [TYPES.WARD_O]: '#a1c4ff',
  [TYPES.WARD_S]: '#7fa8ff',
  [TYPES.COMBO_I]: '#ffd84a',
  [TYPES.COMBO_J]: '#ffd23a',
  [TYPES.COMBO_L]: '#ffdb55',
  [TYPES.COMBO_O]: '#ffce2f',
  [TYPES.COMBO_S]: '#ffe066',
  [TYPES.COMBO_Z]: '#ffd040',
  [TYPES.CRUSHER]: '#5a5f70',
  [TYPES.DISPEL_T]: '#c98bff',
  [TYPES.DISPEL_O]: '#c07bff',
  [TYPES.DISPEL_I]: '#d29bff',
  [TYPES.GARBAGE]: '#4a4b56'
};

export const SHAPE_LIBRARY = {
  I: {
    name: 'I형',
    cells: 4,
    shape: [
    [[0,0,0,0],[1,1,1,1],[0,0,0,0],[0,0,0,0]],
    [[0,0,1,0],[0,0,1,0],[0,0,1,0],[0,0,1,0]],
    [[0,0,0,0],[0,0,0,0],[1,1,1,1],[0,0,0,0]],
    [[0,1,0,0],[0,1,0,0],[0,1,0,0],[0,1,0,0]]
    ]
  },
  J: {
    name: 'J형',
    cells: 4,
    shape: [
    [[1,0,0],[1,1,1],[0,0,0]],
    [[0,1,1],[0,1,0],[0,1,0]],
    [[0,0,0],[1,1,1],[0,0,1]],
    [[0,1,0],[0,1,0],[1,1,0]]
    ]
  },
  L: {
    name: 'L형',
    cells: 4,
    shape: [
    [[0,0,1],[1,1,1],[0,0,0]],
    [[0,1,0],[0,1,0],[0,1,1]],
    [[0,0,0],[1,1,1],[1,0,0]],
    [[1,1,0],[0,1,0],[0,1,0]]
    ]
  },
  O: {
    name: 'O형',
    cells: 4,
    shape: [
    [[1,1],[1,1]], [[1,1],[1,1]], [[1,1],[1,1]], [[1,1],[1,1]]
    ]
  },
  S: {
    name: 'S형',
    cells: 4,
    shape: [
    [[0,1,1],[1,1,0],[0,0,0]],
    [[0,1,0],[0,1,1],[0,0,1]],
    [[0,0,0],[0,1,1],[1,1,0]],
    [[1,0,0],[1,1,0],[0,1,0]]
    ]
  },
  T: {
    name: 'T형',
    cells: 4,
    shape: [
    [[0,1,0],[1,1,1],[0,0,0]],
    [[0,1,0],[0,1,1],[0,1,0]],
    [[0,0,0],[1,1,1],[0,1,0]],
    [[0,1,0],[1,1,0],[0,1,0]]
    ]
  },
  Z: {
    name: 'Z형',
    cells: 4,
    shape: [
    [[1,1,0],[0,1,1],[0,0,0]],
    [[0,0,1],[0,1,1],[0,1,0]],
    [[0,0,0],[1,1,0],[0,1,1]],
    [[0,1,0],[1,1,0],[1,0,0]]
    ]
  },
  CROSS5: {
    name: '크로스형',
    cells: 5,
    shape: [
    [[0,1,0],[1,1,1],[0,1,0]],
    [[0,1,0],[1,1,1],[0,1,0]],
    [[0,1,0],[1,1,1],[0,1,0]],
    [[0,1,0],[1,1,1],[0,1,0]]
    ]
  },
  HEAVY5: {
    name: '헤비형',
    cells: 5,
    shape: [
    [[1,1,1],[0,1,0],[0,1,0]],
    [[0,0,1],[1,1,1],[0,0,1]],
    [[0,1,0],[0,1,0],[1,1,1]],
    [[1,0,0],[1,1,1],[1,0,0]]
    ]
  },
  WIDE6: {
    name: '와이드형',
    cells: 6,
    shape: [
      [[1,1,1,1],[0,1,1,0]],
      [[0,1],[1,1],[1,1],[0,1]],
      [[0,1,1,0],[1,1,1,1]],
      [[1,0],[1,1],[1,1],[1,0]]
    ]
  },
  HOOK5: {
    name: '훅형',
    cells: 5,
    shape: [
      [[1,0,0],[1,0,0],[1,1,1]],
      [[1,1,1],[1,0,0],[1,0,0]],
      [[1,1,1],[0,0,1],[0,0,1]],
      [[0,0,1],[0,0,1],[1,1,1]]
    ]
  },
  PENTA_T: {
    name: 'T펜토형',
    cells: 5,
    shape: [
      [[1,1,1],[0,1,0],[0,1,0]],
      [[0,0,1],[1,1,1],[0,0,1]],
      [[0,1,0],[0,1,0],[1,1,1]],
      [[1,0,0],[1,1,1],[1,0,0]]
    ]
  },
  OVERDRIVE6: {
    name: '오버드라이브형',
    cells: 6,
    shape: [
      [[1,1,0],[0,1,1],[0,1,1]],
      [[0,0,1],[1,1,1],[1,1,0]],
      [[1,1,0],[1,1,0],[0,1,1]],
      [[0,1,1],[1,1,1],[1,0,0]]
    ]
  }
};

export const SHAPES = Object.fromEntries(Object.entries({
  [TYPES.I]: 'I',
  [TYPES.J]: 'J',
  [TYPES.L]: 'L',
  [TYPES.O]: 'O',
  [TYPES.S]: 'S',
  [TYPES.T]: 'T',
  [TYPES.Z]: 'Z',
  [TYPES.POWER_I]: 'I',
  [TYPES.POWER_T]: 'T',
  [TYPES.POWER_S]: 'S',
  [TYPES.CROSS]: 'CROSS5',
  [TYPES.BOMB]: 'O',
  [TYPES.BOMB_I]: 'I',
  [TYPES.MANA_T]: 'T',
  [TYPES.MANA_L]: 'L',
  [TYPES.PURGE_O]: 'O',
  [TYPES.CLEANSE_J]: 'J',
  [TYPES.HEAVY_JUNK]: 'HEAVY5',
  [TYPES.POWER_CROSS]: 'CROSS5',
  [TYPES.WIDE_JUNK]: 'WIDE6',
  [TYPES.INSTANT_STRIKE]: 'HOOK5',
  [TYPES.INSTANT_GUARD]: 'WIDE6',
  [TYPES.INSTANT_MANA]: 'CROSS5',
  [TYPES.INSTANT_PURGE]: 'HEAVY5',
  [TYPES.POWER_Z]: 'Z',
  [TYPES.MANA_Z]: 'Z',
  [TYPES.BOMB_Z]: 'Z',
  [TYPES.CLEANSE_Z]: 'Z',
  [TYPES.POWER_L]: 'L',
  [TYPES.MANA_I]: 'I',
  [TYPES.BOMB_T]: 'T',
  [TYPES.CLEANSE_S]: 'S',
  [TYPES.COOLANT_J]: 'J',
  [TYPES.BOUNTY_O]: 'O',
  [TYPES.WARD_Z]: 'Z',
  [TYPES.WARD_I]: 'I',
  [TYPES.BOMB_J]: 'J',
  [TYPES.BOMB_L]: 'L',
  [TYPES.MANA_O]: 'O',
  [TYPES.BOUNTY_S]: 'S',
  [TYPES.COOLANT_T]: 'T',
  [TYPES.COOLANT_Z]: 'Z',
  [TYPES.POWER_PENTA]: 'PENTA_T',
  [TYPES.COOLANT]: 'I',
  [TYPES.COMBO_CHARGE]: 'T',
  [TYPES.BOUNTY]: 'L',
  [TYPES.UNSTABLE]: 'J',
  [TYPES.LEAD]: 'O',
  [TYPES.WARD_T]: 'T',
  [TYPES.GLASS]: 'S',
  [TYPES.TIMEBOMB]: 'O',
  [TYPES.OVERDRIVE_PENTA]: 'OVERDRIVE6',
  [TYPES.MEGA_CLEANSE]: 'CROSS5',
  [TYPES.PANIC_WALL]: 'WIDE6',
  [TYPES.FLASH_I]: 'I',
  [TYPES.AID_O]: 'O',
  [TYPES.POWER_J]: 'J',
  [TYPES.POWER_O]: 'O',
  [TYPES.BOMB_S]: 'S',
  [TYPES.MANA_J]: 'J',
  [TYPES.MANA_S]: 'S',
  [TYPES.CLEANSE_I]: 'I',
  [TYPES.CLEANSE_L]: 'L',
  [TYPES.CLEANSE_T]: 'T',
  [TYPES.COOLANT_O]: 'O',
  [TYPES.COOLANT_L]: 'L',
  [TYPES.COOLANT_S]: 'S',
  [TYPES.BOUNTY_I]: 'I',
  [TYPES.BOUNTY_J]: 'J',
  [TYPES.BOUNTY_T]: 'T',
  [TYPES.BOUNTY_Z]: 'Z',
  [TYPES.WARD_J]: 'J',
  [TYPES.WARD_L]: 'L',
  [TYPES.WARD_O]: 'O',
  [TYPES.WARD_S]: 'S',
  [TYPES.COMBO_I]: 'I',
  [TYPES.COMBO_J]: 'J',
  [TYPES.COMBO_L]: 'L',
  [TYPES.COMBO_O]: 'O',
  [TYPES.COMBO_S]: 'S',
  [TYPES.COMBO_Z]: 'Z',
  [TYPES.CRUSHER]: 'O',
  [TYPES.DISPEL_T]: 'T',
  [TYPES.DISPEL_O]: 'O',
  [TYPES.DISPEL_I]: 'I'
}).map(([id, shapeId]) => [id, SHAPE_LIBRARY[shapeId].shape]));

// 능력별 표시 글리프(블록 셀·DOM 공용). 작은 셀에서도 또렷하도록 단색 유니코드 기호를 쓴다.
export const ABILITY_GLYPH = {
  highPower: '✦', oddPower: '✦', overdrive: '✦',
  bomb: '✸', timeBomb: '◷',
  manaBonus: '◆', instantMana: '◆',
  purgeGarbage: '✚', instantPurge: '✚', megaCleanse: '✚', aidCleanse: '✚',
  instantAttack: '➤', flashStrike: '➤',
  instantGuard: '▣', panicWall: '▣', wardBlock: '⊟',
  coolant: '✻', comboCharge: '✖', bounty: '$', leadPower: '▼',
  unstable: '?', glass: '◈', crush: '▽', dispel: '✺',
  curse: '⊘', wideCurse: '⊘'
};

export const ABILITY_LIBRARY = {
  none: { id: 'none', name: '일반', cellAttack: 0.1, traits: [], desc: '기본 테트로미노 셀.' },
  highPower: { id: 'highPower', name: '고출력', cellAttack: 0.3, traits: ['highPower'], desc: '클리어된 셀당 0.3 공격력.' },
  oddPower: { id: 'oddPower', name: '고효율', cellAttack: 0.16, traits: ['oddShape'], desc: '배치가 까다로운 대신 기본보다 높은 공격력을 가집니다.' },
  bomb: { id: 'bomb', name: '폭탄', cellAttack: 0.1, traits: ['bomb'], desc: '클리어 시 중심 3×3 영역을 파괴합니다.' },
  manaBonus: { id: 'manaBonus', name: '마나', cellAttack: 0.1, traits: ['manaBonus'], desc: '클리어된 셀이 추가 MP를 제공합니다.' },
  purgeGarbage: { id: 'purgeGarbage', name: '클렌즈', cellAttack: 0.1, traits: ['purgeGarbage'], desc: '줄을 지울 때 그 줄에 포함된 클렌즈 칸 수만큼 내 필드의 쓰레기 행을 제거합니다(칸당 1줄).' },
  instantAttack: { id: 'instantAttack', name: '즉발 공격', cellAttack: 0.1, traits: [], onPlace: { attack: 1.2 }, desc: '배치 즉시 1.2 공격력을 발사합니다.' },
  instantGuard: { id: 'instantGuard', name: '즉발 방어', cellAttack: 0.1, traits: [], onPlace: { cancelGarbage: 3 }, desc: '배치 즉시 들어오는 공격 게이지를 최대 3 차단합니다.' },
  instantMana: { id: 'instantMana', name: '즉발 마나', cellAttack: 0.1, traits: [], onPlace: { mana: 18 }, desc: '배치 즉시 MP를 18 회복합니다.' },
  instantPurge: { id: 'instantPurge', name: '즉발 퍼지', cellAttack: 0.1, traits: [], onPlace: { purgeGarbageRows: 1 }, desc: '배치 즉시 쓰레기 행 1줄을 제거합니다.' },
  curse: { id: 'curse', name: '방해', cellAttack: 0.1, traits: ['curse'], desc: '덱을 막는 방해형 블록.' },
  wideCurse: { id: 'wideCurse', name: '광역 방해', cellAttack: 0.1, traits: ['curse', 'wide'], desc: '덱을 막는 6칸 방해형 블록.' },
  coolant: { id: 'coolant', name: '냉각', cellAttack: 0.1, traits: ['coolant'], desc: '라인 클리어 시 적의 행동 속도를 잠시 늦춥니다.' },
  comboCharge: { id: 'comboCharge', name: '콤보 차지', cellAttack: 0.1, traits: ['comboCharge'], desc: '클리어 시 다음 클리어의 공격력이 누적 증가합니다.' },
  bounty: { id: 'bounty', name: '현상금', cellAttack: 0.1, traits: ['bounty'], desc: '라인 클리어 시 골드를 획득합니다.' },
  unstable: { id: 'unstable', name: '불안정', cellAttack: 0.1, traits: ['unstable'], onPlace: { selfGarbage: 1, enemyGarbage: 1 }, penalty: true, desc: '배치 시 내 필드와 적 필드에 각각 쓰레기 1줄이 추가됩니다.' },
  leadPower: { id: 'leadPower', name: '중량', cellAttack: 0.5, traits: ['heavy'], penalty: true, desc: '셀당 0.5 공격력. 착지 즉시 고정되며 홀드할 수 없습니다.' },
  wardBlock: { id: 'wardBlock', name: '차단', cellAttack: 0, traits: ['wardBlock'], onPlace: { cancelGarbage: 2 }, desc: '배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.' },
  glass: { id: 'glass', name: '유리', cellAttack: 0.5, traits: ['glass'], penalty: true, desc: '셀당 0.5 공격력. 이 블록을 하드드롭하거나 다른 블록이 이 블록 바로 위로 하드드롭되면 깨져 빈칸이 됩니다. 소프트드롭으로 내리면 유지됩니다.' },
  timeBomb: { id: 'timeBomb', name: '시한폭탄', cellAttack: 0.1, traits: ['timeBomb'], fuse: 5, penalty: true, desc: '배치 후 매 턴 카운트다운. 0이 되면 그 칸만 사라지고, 줄로 제거하면 5×5 대폭발.' },
  overdrive: { id: 'overdrive', name: '오버드라이브', cellAttack: 0.1, traits: [], onPlace: { attack: 4 }, desc: '배치 즉시 4.0 공격력을 발사합니다.' },
  megaCleanse: { id: 'megaCleanse', name: '메가 클렌즈', cellAttack: 0.1, traits: [], onPlace: { purgeGarbageRows: 6 }, desc: '배치 즉시 쓰레기 행 6줄을 제거합니다.' },
  panicWall: { id: 'panicWall', name: '패닉 월', cellAttack: 0.1, traits: [], onPlace: { cancelGarbage: 8 }, desc: '배치 즉시 들어오는 공격 게이지를 최대 8 차단합니다.' },
  flashStrike: { id: 'flashStrike', name: '섬광', cellAttack: 0.1, traits: [], onPlace: { attack: 2 }, desc: '배치 즉시 2.0 공격력을 발사합니다.' },
  aidCleanse: { id: 'aidCleanse', name: '응급 클렌즈', cellAttack: 0.1, traits: [], onPlace: { purgeGarbageRows: 2 }, desc: '배치 즉시 쓰레기 행 2줄을 제거합니다.' },
  crush: { id: 'crush', name: '중량', cellAttack: 0.3, traits: ['heavyCrush'], desc: '놓는 순간 점유한 각 열의 빈칸을 모두 눌러 없앱니다(아래로 압착).' },
  dispel: { id: 'dispel', name: '해제', cellAttack: 0.1, traits: [], onPlace: { dispelEnemy: true }, desc: '배치 즉시 적의 현재 특수능력을 일시 제거하고 게이지를 비웁니다.' }
};

function tierFromShapeAbility(shapeId, abilityId, rarity) {
  const strongAbilities = new Set([
    'highPower',
    'bomb',
    'purgeGarbage',
    'comboCharge',
    'wardBlock',
    'leadPower',
    'timeBomb',
    'overdrive',
    'megaCleanse',
    'panicWall'
  ]);
  if (rarity === 'curse') return TIERS.BRONZE;
  if (shapeId === 'I') return TIERS.GOLD;
  if (['J', 'L', 'T'].includes(shapeId)) return strongAbilities.has(abilityId) ? TIERS.GOLD : TIERS.SILVER;
  if (['S', 'Z', 'CROSS5', 'HEAVY5', 'WIDE6', 'HOOK5', 'PENTA_T'].includes(shapeId)) {
    return abilityId === 'none' ? TIERS.BRONZE : TIERS.SILVER;
  }
  if (rarity === 'gold' || rarity === 'rare') return TIERS.GOLD;
  if (rarity === 'silver' || rarity === 'uncommon') return TIERS.SILVER;
  return TIERS.BRONZE;
}

function blockCard(id, name, shapeId, abilityId = 'none', rarity = 'base', opts = {}) {
  const shape = SHAPE_LIBRARY[shapeId];
  const ability = ABILITY_LIBRARY[abilityId];
  const traits = [...ability.traits];
  if (opts.exhaust) traits.push('exhaust');
  return {
    id,
    name,
    shapeId,
    shapeName: shape.name,
    abilityId,
    abilityName: ability.name,
    cellCount: shape.cells,
    shape: shape.shape,
    cellAttack: ability.cellAttack,
    traits,
    onPlace: ability.onPlace ? { ...ability.onPlace } : null,
    penalty: !!ability.penalty,
    fuse: ability.fuse || 0,
    exhaust: !!opts.exhaust,
    rarity,
    tier: tierFromShapeAbility(shapeId, abilityId, rarity)
  };
};

export const CARD_LIBRARY = {
  [TYPES.I]: blockCard(TYPES.I, 'I Mino', 'I'),
  [TYPES.J]: blockCard(TYPES.J, 'J Mino', 'J'),
  [TYPES.L]: blockCard(TYPES.L, 'L Mino', 'L'),
  [TYPES.O]: blockCard(TYPES.O, 'O 미노', 'O'),
  [TYPES.S]: blockCard(TYPES.S, 'S 미노', 'S'),
  [TYPES.T]: blockCard(TYPES.T, 'T 미노', 'T'),
  [TYPES.Z]: blockCard(TYPES.Z, 'Z 미노', 'Z'),
  [TYPES.POWER_I]: blockCard(TYPES.POWER_I, '파워 I', 'I', 'highPower', 'rare'),
  [TYPES.POWER_T]: blockCard(TYPES.POWER_T, '파워 T', 'T', 'highPower', 'rare'),
  [TYPES.POWER_S]: blockCard(TYPES.POWER_S, '파워 S', 'S', 'highPower', 'rare'),
  [TYPES.CROSS]: blockCard(TYPES.CROSS, '크로스 미노', 'CROSS5', 'oddPower', 'rare'),
  [TYPES.BOMB]: blockCard(TYPES.BOMB, '봄브 O', 'O', 'bomb', 'uncommon'),
  [TYPES.BOMB_I]: blockCard(TYPES.BOMB_I, '봄브 I', 'I', 'bomb', 'rare'),
  [TYPES.MANA_T]: blockCard(TYPES.MANA_T, '마나 T', 'T', 'manaBonus', 'uncommon'),
  [TYPES.MANA_L]: blockCard(TYPES.MANA_L, '마나 L', 'L', 'manaBonus', 'uncommon'),
  [TYPES.PURGE_O]: blockCard(TYPES.PURGE_O, '클렌즈 O', 'O', 'purgeGarbage', 'rare'),
  [TYPES.CLEANSE_J]: blockCard(TYPES.CLEANSE_J, '클렌즈 J', 'J', 'purgeGarbage', 'rare'),
  [TYPES.HEAVY_JUNK]: blockCard(TYPES.HEAVY_JUNK, '헤비 정크', 'HEAVY5', 'curse', 'curse'),
  [TYPES.POWER_CROSS]: blockCard(TYPES.POWER_CROSS, '파워 크로스', 'CROSS5', 'highPower', 'rare'),
  [TYPES.WIDE_JUNK]: blockCard(TYPES.WIDE_JUNK, '와이드 정크', 'WIDE6', 'wideCurse', 'curse'),
  [TYPES.INSTANT_STRIKE]: blockCard(TYPES.INSTANT_STRIKE, '스트라이크 훅', 'HOOK5', 'instantAttack', 'uncommon'),
  [TYPES.INSTANT_GUARD]: blockCard(TYPES.INSTANT_GUARD, '가드 와이드', 'WIDE6', 'instantGuard', 'uncommon'),
  [TYPES.INSTANT_MANA]: blockCard(TYPES.INSTANT_MANA, '마나 크로스', 'CROSS5', 'instantMana', 'uncommon'),
  [TYPES.INSTANT_PURGE]: blockCard(TYPES.INSTANT_PURGE, '퍼지 헤비', 'HEAVY5', 'instantPurge', 'rare'),
  [TYPES.POWER_Z]: blockCard(TYPES.POWER_Z, '파워 Z', 'Z', 'highPower', 'rare'),
  [TYPES.MANA_Z]: blockCard(TYPES.MANA_Z, '마나 Z', 'Z', 'manaBonus', 'uncommon'),
  [TYPES.BOMB_Z]: blockCard(TYPES.BOMB_Z, '봄브 Z', 'Z', 'bomb', 'uncommon'),
  [TYPES.CLEANSE_Z]: blockCard(TYPES.CLEANSE_Z, '클렌즈 Z', 'Z', 'purgeGarbage', 'rare'),
  [TYPES.POWER_L]: blockCard(TYPES.POWER_L, '파워 L', 'L', 'highPower', 'rare'),
  [TYPES.MANA_I]: blockCard(TYPES.MANA_I, '마나 I', 'I', 'manaBonus', 'rare'),
  [TYPES.BOMB_T]: blockCard(TYPES.BOMB_T, '봄브 T', 'T', 'bomb', 'rare'),
  [TYPES.CLEANSE_S]: blockCard(TYPES.CLEANSE_S, '클렌즈 S', 'S', 'purgeGarbage', 'uncommon'),
  [TYPES.COOLANT_J]: blockCard(TYPES.COOLANT_J, '냉각 J', 'J', 'coolant', 'uncommon'),
  [TYPES.BOUNTY_O]: blockCard(TYPES.BOUNTY_O, '현상금 O', 'O', 'bounty', 'uncommon'),
  [TYPES.WARD_Z]: blockCard(TYPES.WARD_Z, '차단 Z', 'Z', 'wardBlock', 'rare'),
  [TYPES.WARD_I]: blockCard(TYPES.WARD_I, '차단 I', 'I', 'wardBlock', 'rare'),
  [TYPES.BOMB_J]: blockCard(TYPES.BOMB_J, '봄브 J', 'J', 'bomb', 'rare'),
  [TYPES.BOMB_L]: blockCard(TYPES.BOMB_L, '봄브 L', 'L', 'bomb', 'rare'),
  [TYPES.MANA_O]: blockCard(TYPES.MANA_O, '마나 O', 'O', 'manaBonus', 'uncommon'),
  [TYPES.BOUNTY_S]: blockCard(TYPES.BOUNTY_S, '현상금 S', 'S', 'bounty', 'uncommon'),
  [TYPES.COOLANT_T]: blockCard(TYPES.COOLANT_T, '냉각 T', 'T', 'coolant', 'uncommon'),
  [TYPES.COOLANT_Z]: blockCard(TYPES.COOLANT_Z, '냉각 Z', 'Z', 'coolant', 'uncommon'),
  [TYPES.POWER_PENTA]: blockCard(TYPES.POWER_PENTA, '파워 펜토', 'PENTA_T', 'highPower', 'rare'),
  [TYPES.COOLANT]: blockCard(TYPES.COOLANT, '냉각 I', 'I', 'coolant', 'uncommon'),
  [TYPES.COMBO_CHARGE]: blockCard(TYPES.COMBO_CHARGE, '콤보 T', 'T', 'comboCharge', 'rare'),
  [TYPES.BOUNTY]: blockCard(TYPES.BOUNTY, '현상금 L', 'L', 'bounty', 'uncommon'),
  [TYPES.UNSTABLE]: blockCard(TYPES.UNSTABLE, '불안정 J', 'J', 'unstable', 'rare'),
  [TYPES.LEAD]: blockCard(TYPES.LEAD, '납 O', 'O', 'leadPower', 'rare'),
  [TYPES.WARD_T]: blockCard(TYPES.WARD_T, '차단 T', 'T', 'wardBlock', 'rare'),
  [TYPES.GLASS]: blockCard(TYPES.GLASS, '유리 S', 'S', 'glass', 'rare'),
  [TYPES.TIMEBOMB]: blockCard(TYPES.TIMEBOMB, '시한폭탄 O', 'O', 'timeBomb', 'rare'),
  [TYPES.OVERDRIVE_PENTA]: blockCard(TYPES.OVERDRIVE_PENTA, '오버드라이브 헥사', 'OVERDRIVE6', 'overdrive', 'rare', { exhaust: true }),
  [TYPES.MEGA_CLEANSE]: blockCard(TYPES.MEGA_CLEANSE, '메가 클렌즈', 'CROSS5', 'megaCleanse', 'rare', { exhaust: true }),
  [TYPES.PANIC_WALL]: blockCard(TYPES.PANIC_WALL, '패닉 월', 'WIDE6', 'panicWall', 'uncommon', { exhaust: true }),
  [TYPES.FLASH_I]: blockCard(TYPES.FLASH_I, '섬광 I', 'I', 'flashStrike', 'uncommon', { exhaust: true }),
  [TYPES.AID_O]: blockCard(TYPES.AID_O, '응급 클렌즈', 'O', 'aidCleanse', 'uncommon', { exhaust: true }),
  [TYPES.POWER_J]: blockCard(TYPES.POWER_J, '파워 J', 'J', 'highPower', 'rare'),
  [TYPES.POWER_O]: blockCard(TYPES.POWER_O, '파워 O', 'O', 'highPower', 'rare'),
  [TYPES.BOMB_S]: blockCard(TYPES.BOMB_S, '봄브 S', 'S', 'bomb', 'uncommon'),
  [TYPES.MANA_J]: blockCard(TYPES.MANA_J, '마나 J', 'J', 'manaBonus', 'uncommon'),
  [TYPES.MANA_S]: blockCard(TYPES.MANA_S, '마나 S', 'S', 'manaBonus', 'uncommon'),
  [TYPES.CLEANSE_I]: blockCard(TYPES.CLEANSE_I, '클렌즈 I', 'I', 'purgeGarbage', 'rare'),
  [TYPES.CLEANSE_L]: blockCard(TYPES.CLEANSE_L, '클렌즈 L', 'L', 'purgeGarbage', 'uncommon'),
  [TYPES.CLEANSE_T]: blockCard(TYPES.CLEANSE_T, '클렌즈 T', 'T', 'purgeGarbage', 'uncommon'),
  [TYPES.COOLANT_O]: blockCard(TYPES.COOLANT_O, '냉각 O', 'O', 'coolant', 'uncommon'),
  [TYPES.COOLANT_L]: blockCard(TYPES.COOLANT_L, '냉각 L', 'L', 'coolant', 'uncommon'),
  [TYPES.COOLANT_S]: blockCard(TYPES.COOLANT_S, '냉각 S', 'S', 'coolant', 'uncommon'),
  [TYPES.BOUNTY_I]: blockCard(TYPES.BOUNTY_I, '현상금 I', 'I', 'bounty', 'uncommon'),
  [TYPES.BOUNTY_J]: blockCard(TYPES.BOUNTY_J, '현상금 J', 'J', 'bounty', 'uncommon'),
  [TYPES.BOUNTY_T]: blockCard(TYPES.BOUNTY_T, '현상금 T', 'T', 'bounty', 'uncommon'),
  [TYPES.BOUNTY_Z]: blockCard(TYPES.BOUNTY_Z, '현상금 Z', 'Z', 'bounty', 'uncommon'),
  [TYPES.WARD_J]: blockCard(TYPES.WARD_J, '차단 J', 'J', 'wardBlock', 'rare'),
  [TYPES.WARD_L]: blockCard(TYPES.WARD_L, '차단 L', 'L', 'wardBlock', 'rare'),
  [TYPES.WARD_O]: blockCard(TYPES.WARD_O, '차단 O', 'O', 'wardBlock', 'rare'),
  [TYPES.WARD_S]: blockCard(TYPES.WARD_S, '차단 S', 'S', 'wardBlock', 'rare'),
  [TYPES.COMBO_I]: blockCard(TYPES.COMBO_I, '콤보 I', 'I', 'comboCharge', 'rare'),
  [TYPES.COMBO_J]: blockCard(TYPES.COMBO_J, '콤보 J', 'J', 'comboCharge', 'rare'),
  [TYPES.COMBO_L]: blockCard(TYPES.COMBO_L, '콤보 L', 'L', 'comboCharge', 'rare'),
  [TYPES.COMBO_O]: blockCard(TYPES.COMBO_O, '콤보 O', 'O', 'comboCharge', 'rare'),
  [TYPES.COMBO_S]: blockCard(TYPES.COMBO_S, '콤보 S', 'S', 'comboCharge', 'rare'),
  [TYPES.COMBO_Z]: blockCard(TYPES.COMBO_Z, '콤보 Z', 'Z', 'comboCharge', 'rare'),
  [TYPES.CRUSHER]: blockCard(TYPES.CRUSHER, '중량 블록', 'O', 'crush', 'gold', { exhaust: true }),
  [TYPES.DISPEL_T]: blockCard(TYPES.DISPEL_T, '해제 T', 'T', 'dispel', 'rare'),
  [TYPES.DISPEL_O]: blockCard(TYPES.DISPEL_O, '해제 O', 'O', 'dispel', 'rare'),
  [TYPES.DISPEL_I]: blockCard(TYPES.DISPEL_I, '해제 I', 'I', 'dispel', 'rare')
};

export const CARD_DESCRIPTIONS = {
  [TYPES.I]: '긴 4칸 직선 블록. 한 번에 넓은 줄을 메우기 좋습니다.',
  [TYPES.J]: '꺾인 4칸 블록. 구석과 계단 지형을 메우기 좋습니다.',
  [TYPES.L]: '반대 방향으로 꺾인 4칸 블록. 측면 정리에 유리합니다.',
  [TYPES.O]: '2x2 사각 블록. 안정적이지만 구멍 정리는 어렵습니다.',
  [TYPES.S]: '엇갈린 4칸 블록. 낮은 지형에서는 좋지만 배치가 까다롭습니다.',
  [TYPES.T]: '중앙 돌출 4칸 블록. T스핀과 구멍 메우기에 강합니다.',
  [TYPES.Z]: 'S와 반대 방향의 엇갈린 4칸 블록. 배치 난도가 높습니다.',
  [TYPES.POWER_I]: 'I 모양 고출력 블록. 클리어된 셀당 0.3 공격력.',
  [TYPES.POWER_T]: 'T 모양 고출력 블록. T스핀 클리어와 공격 전환에 강합니다.',
  [TYPES.POWER_S]: 'S 모양 고출력 블록. 까다롭지만 클리어 시 공격력이 높습니다.',
  [TYPES.CROSS]: '5칸 십자형 블록. 배치 난도가 높지만 칸당 공격력이 기본 블록보다 높습니다.',
  [TYPES.BOMB]: 'O 모양 폭탄. 줄 클리어 시 주변 3x3을 파괴합니다.',
  [TYPES.BOMB_I]: 'I 모양 폭탄. 줄 클리어 시 주변 3x3을 파괴합니다.',
  [TYPES.MANA_T]: 'T 모양 마나 블록. 클리어된 셀이 추가 MP를 제공합니다.',
  [TYPES.MANA_L]: 'L 모양 마나 블록. 클리어 시 MP 수급에 좋습니다.',
  [TYPES.PURGE_O]: 'O 모양 클렌즈. 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.CLEANSE_J]: 'J 모양 클렌즈. 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.HEAVY_JUNK]: '5칸 방해 블록. 덱을 무겁게 만들고 배치가 까다롭습니다.',
  [TYPES.POWER_CROSS]: '십자형 고출력 블록. 특이한 모양이지만 공격력이 높습니다.',
  [TYPES.WIDE_JUNK]: '6칸 방해 블록. 넓고 까다로운 모양으로 덱을 막습니다.',
  [TYPES.INSTANT_STRIKE]: '배치 즉시 1.2 공격력을 발사하는 훅 모양 블록.',
  [TYPES.INSTANT_GUARD]: '배치 즉시 들어오는 공격 게이지를 최대 3 차단합니다.',
  [TYPES.INSTANT_MANA]: '배치 즉시 MP를 18 회복하는 십자형 블록.',
  [TYPES.INSTANT_PURGE]: '배치 즉시 쓰레기 행 1줄을 제거하는 헤비 블록.',
  [TYPES.POWER_Z]: 'Z 모양 고출력 블록. 어려운 모양 대신 클리어 공격력이 높습니다.',
  [TYPES.MANA_Z]: 'Z 모양 마나 블록. 까다로운 배치로 MP를 추가 수급합니다.',
  [TYPES.BOMB_Z]: 'Z 모양 폭탄. 줄 클리어 시 주변 3x3을 파괴합니다.',
  [TYPES.CLEANSE_Z]: 'Z 모양 클렌즈. 줄 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.POWER_L]: 'L 모양 고출력 블록. 측면 정리와 공격 전환에 강합니다.',
  [TYPES.MANA_I]: 'I 모양 마나 블록. 긴 줄 클리어로 MP를 크게 수급합니다.',
  [TYPES.BOMB_T]: 'T 모양 폭탄. T 배치로 줄을 지우면 주변 3x3을 파괴합니다.',
  [TYPES.CLEANSE_S]: 'S 모양 클렌즈. 까다로운 모양이지만 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.COOLANT_J]: 'J 모양 냉각 블록. 클리어된 냉각 셀마다 적 행동을 0.5초 늦춥니다.',
  [TYPES.BOUNTY_O]: 'O 모양 현상금 블록. 안정적으로 골드를 노릴 수 있습니다.',
  [TYPES.WARD_Z]: 'Z 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.WARD_I]: 'I 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.BOMB_J]: 'J 모양 폭탄. 구석 정리 중 주변 3x3 파괴를 노릴 수 있습니다.',
  [TYPES.BOMB_L]: 'L 모양 폭탄. 측면 정리와 폭발 정리를 함께 노립니다.',
  [TYPES.MANA_O]: 'O 모양 마나 블록. 안정적인 2x2 배치로 MP를 추가 수급합니다.',
  [TYPES.BOUNTY_S]: 'S 모양 현상금 블록. 까다로운 배치 보상으로 골드를 얻습니다.',
  [TYPES.COOLANT_T]: 'T 모양 냉각 블록. T 배치로 클리어하면 적 행동을 늦춥니다.',
  [TYPES.COOLANT_Z]: 'Z 모양 냉각 블록. 까다로운 배치 대신 적 행동 지연을 얻습니다.',
  [TYPES.POWER_PENTA]: '5칸 펜토 고출력 블록. 모양은 어렵지만 공격 효율이 좋습니다.',
  [TYPES.COOLANT]: 'I 모양 냉각 블록. 클리어된 냉각 셀마다 적 행동을 0.5초 늦춥니다.',
  [TYPES.COMBO_CHARGE]: 'T 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.BOUNTY]: 'L 모양 현상금 블록. 클리어된 현상금 셀 수에 따라 골드를 얻습니다.',
  [TYPES.UNSTABLE]: 'J 모양 불안정 블록. 배치 시 양쪽 필드에 쓰레기 1줄을 예약합니다.',
  [TYPES.LEAD]: 'O 모양 납 블록. 셀당 0.5 공격력이며 홀드할 수 없고 착지 즉시 고정됩니다.',
  [TYPES.WARD_T]: 'T 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.GLASS]: 'S 모양 유리 블록. 셀당 0.5 공격력. 이 블록을 하드드롭하거나 다른 블록이 바로 위로 하드드롭되면 깨져 빈칸이 됩니다. 소프트드롭으로 내려야 유지됩니다.',
  [TYPES.TIMEBOMB]: 'O 모양 시한폭탄. 매 턴 카운트다운하고, 줄로 제거되면 5x5로 폭발합니다.',
  [TYPES.OVERDRIVE_PENTA]: '[1회용·골드] 배치 즉시 4.0 공격력을 발사하는 6칸 변칙 블록. 모양이 까다로워 자리 잡기 어렵고, 전투당 한 번만 등장합니다.',
  [TYPES.MEGA_CLEANSE]: '[1회용] 배치 즉시 쓰레기 행 6줄을 제거합니다. 전투당 한 번만 등장합니다.',
  [TYPES.PANIC_WALL]: '[1회용] 배치 즉시 들어오는 공격 게이지를 최대 8 차단합니다. 전투당 한 번만 등장합니다.',
  [TYPES.FLASH_I]: '[소멸] 배치 즉시 2.0 공격력을 발사합니다. 전투당 한 번만 등장합니다.',
  [TYPES.AID_O]: '[소멸] 배치 즉시 쓰레기 행 2줄을 제거합니다. 전투당 한 번만 등장합니다.',
  [TYPES.POWER_J]: 'J 모양 고출력 블록. 클리어된 셀당 0.3 공격력.',
  [TYPES.POWER_O]: 'O 모양 고출력 블록. 클리어된 셀당 0.3 공격력.',
  [TYPES.BOMB_S]: 'S 모양 폭탄. 줄 클리어 시 주변 3x3을 파괴합니다.',
  [TYPES.MANA_J]: 'J 모양 마나 블록. 클리어된 셀이 추가 MP를 제공합니다.',
  [TYPES.MANA_S]: 'S 모양 마나 블록. 클리어된 셀이 추가 MP를 제공합니다.',
  [TYPES.CLEANSE_I]: 'I 모양 클렌즈 블록. 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.CLEANSE_L]: 'L 모양 클렌즈 블록. 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.CLEANSE_T]: 'T 모양 클렌즈 블록. 클리어 시 쓰레기 행을 제거합니다.',
  [TYPES.COOLANT_O]: 'O 모양 냉각 블록. 클리어된 냉각 셀마다 적 행동을 늦춥니다.',
  [TYPES.COOLANT_L]: 'L 모양 냉각 블록. 클리어된 냉각 셀마다 적 행동을 늦춥니다.',
  [TYPES.COOLANT_S]: 'S 모양 냉각 블록. 클리어된 냉각 셀마다 적 행동을 늦춥니다.',
  [TYPES.BOUNTY_I]: 'I 모양 현상금 블록. 클리어된 현상금 셀 수에 따라 골드를 얻습니다.',
  [TYPES.BOUNTY_J]: 'J 모양 현상금 블록. 클리어된 현상금 셀 수에 따라 골드를 얻습니다.',
  [TYPES.BOUNTY_T]: 'T 모양 현상금 블록. 클리어된 현상금 셀 수에 따라 골드를 얻습니다.',
  [TYPES.BOUNTY_Z]: 'Z 모양 현상금 블록. 클리어된 현상금 셀 수에 따라 골드를 얻습니다.',
  [TYPES.WARD_J]: 'J 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.WARD_L]: 'L 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.WARD_O]: 'O 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.WARD_S]: 'S 모양 차단 블록. 배치 즉시 게이지에 쌓인 적 공격 2줄을 차단(제거)합니다. 줄로 지워도 공격력은 0입니다.',
  [TYPES.COMBO_I]: 'I 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.COMBO_J]: 'J 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.COMBO_L]: 'L 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.COMBO_O]: 'O 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.COMBO_S]: 'S 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.COMBO_Z]: 'Z 모양 콤보 차지. 클리어 시 다음 클리어 공격력이 누적 증가합니다.',
  [TYPES.CRUSHER]: '[소멸·골드] 중량 블록. 놓는 순간 점유한 각 열의 빈칸을 모두 눌러 없앱니다(아래로 압착). 구멍 복구에 최적. 전투당 한 번만 등장합니다.',
  [TYPES.DISPEL_T]: 'T 모양 해제 블록. 배치 즉시 적의 현재 특수능력을 일시 제거하고 능력 게이지를 비웁니다(보스 OVERLOAD 포함).',
  [TYPES.DISPEL_O]: 'O 모양 해제 블록. 배치 즉시 적의 현재 특수능력을 일시 제거하고 능력 게이지를 비웁니다(보스 OVERLOAD 포함).',
  [TYPES.DISPEL_I]: 'I 모양 해제 블록. 배치 즉시 적의 현재 특수능력을 일시 제거하고 능력 게이지를 비웁니다(보스 OVERLOAD 포함).'
};

export const SET_DEFINITIONS = {
  highPower: { I: TYPES.POWER_I, J: TYPES.POWER_J, L: TYPES.POWER_L, O: TYPES.POWER_O, S: TYPES.POWER_S, T: TYPES.POWER_T, Z: TYPES.POWER_Z },
  bomb: { I: TYPES.BOMB_I, J: TYPES.BOMB_J, L: TYPES.BOMB_L, O: TYPES.BOMB, S: TYPES.BOMB_S, T: TYPES.BOMB_T, Z: TYPES.BOMB_Z },
  manaBonus: { I: TYPES.MANA_I, J: TYPES.MANA_J, L: TYPES.MANA_L, O: TYPES.MANA_O, S: TYPES.MANA_S, T: TYPES.MANA_T, Z: TYPES.MANA_Z },
  purgeGarbage: { I: TYPES.CLEANSE_I, J: TYPES.CLEANSE_J, L: TYPES.CLEANSE_L, O: TYPES.PURGE_O, S: TYPES.CLEANSE_S, T: TYPES.CLEANSE_T, Z: TYPES.CLEANSE_Z },
  coolant: { I: TYPES.COOLANT, J: TYPES.COOLANT_J, L: TYPES.COOLANT_L, O: TYPES.COOLANT_O, S: TYPES.COOLANT_S, T: TYPES.COOLANT_T, Z: TYPES.COOLANT_Z },
  bounty: { I: TYPES.BOUNTY_I, J: TYPES.BOUNTY_J, L: TYPES.BOUNTY, O: TYPES.BOUNTY_O, S: TYPES.BOUNTY_S, T: TYPES.BOUNTY_T, Z: TYPES.BOUNTY_Z },
  wardBlock: { I: TYPES.WARD_I, J: TYPES.WARD_J, L: TYPES.WARD_L, O: TYPES.WARD_O, S: TYPES.WARD_S, T: TYPES.WARD_T, Z: TYPES.WARD_Z },
  comboCharge: { I: TYPES.COMBO_I, J: TYPES.COMBO_J, L: TYPES.COMBO_L, O: TYPES.COMBO_O, S: TYPES.COMBO_S, T: TYPES.COMBO_CHARGE, Z: TYPES.COMBO_Z }
};

export const SET_RELICS = {
  highPower: 'set_overload',
  bomb: 'set_blastcap',
  manaBonus: 'set_manawell',
  purgeGarbage: 'set_sanctuary',
  coolant: 'set_abszero',
  bounty: 'set_goldhand',
  wardBlock: 'set_bulwark',
  comboCharge: 'set_comboengine'
};

export const SET_LABELS = {
  highPower: '파워', bomb: '봄브', manaBonus: '마나', purgeGarbage: '클렌즈',
  coolant: '냉각', bounty: '현상금', wardBlock: '차단', comboCharge: '콤보'
};
